// GENERATED by scripts/gen-catalog.mjs from n8n node "Feed List Code" — do not hand-edit.
// To add a source, edit src/catalog/feeds.extra.ts instead (see README).
import type { FeedDef } from './types.js';

export const FEEDS: FeedDef[] = [

  // ════════════════════════════════════════════════════════
  // 🎮 GAMING — RSS
  // ════════════════════════════════════════════════════════
  { name: 'PlayStation Blog', category: 'Gaming', type: 'rss',
    url: 'http://feeds.feedburner.com/psblog' },
  { name: 'Nintendo', category: 'Gaming', type: 'rss',
    url: 'https://www.nintendo.com/en-gb/news.xml' },
  { name: 'Xbox Wire', category: 'Gaming', type: 'rss',
    url: 'https://news.xbox.com/en-us/feed' },
  { name: 'Steam News', category: 'Gaming', type: 'rss',
    url: 'https://store.steampowered.com/feeds/news.xml' },
  { name: 'IGN', category: 'Gaming', type: 'rss',
    url: 'http://feeds.ign.com/ign/all' },
  { name: 'Kotaku', category: 'Gaming', type: 'rss',
    url: 'https://kotaku.com/rss' },
  { name: 'Polygon', category: 'Gaming', type: 'rss',
    url: 'https://www.polygon.com/rss/index.xml' },
  { name: 'Eurogamer', category: 'Gaming', type: 'rss',
    url: 'https://www.eurogamer.net/?format=rss' },
  { name: 'Rock Paper Shotgun', category: 'Gaming', type: 'rss',
    url: 'https://www.rockpapershotgun.com/feed' },
  { name: 'PC Gamer', category: 'Gaming', type: 'rss',
    url: 'https://www.pcgamer.com/rss/' },
  { name: 'Reddit r/games', category: 'Gaming', type: 'rss',
    url: 'https://www.reddit.com/r/games/.rss' },

  // ════════════════════════════════════════════════════════
  // 🎮 GAMING — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'IGN YouTube', sourceKey: 'IGN', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCKy1dAqELo0zrOtPkf0eTMw' },
  { name: 'Xbox YouTube', sourceKey: 'Xbox', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCydtMNspoPAlqBjFSGnigSw' },
  { name: 'Valve YouTube', sourceKey: 'Valve', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UChmZ6QbxgHlmX3ISIHxIpQQ' },
  { name: 'FromSoftware YouTube', sourceKey: 'FromSoftware', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCCkxMbfZ80VFwwiRlIG5P5g' },
  { name: 'Rockstar Games YouTube', sourceKey: 'Rockstar Games', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCULwHhkI31JHAKe57LZdzcA' },
  { name: 'PlayStation YouTube', sourceKey: 'PlayStation', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBsbrudhKRrT9zs8iNOEjjw' },
  { name: 'Bandai Namco YouTube', sourceKey: 'Bandai Namco', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_ntXHv-XdKCD7CPynVvnQw' },
  { name: 'WB Games YouTube', sourceKey: 'WB Games', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNflpbEsoC9uWkSPrx6hMqg' },
  { name: 'Nintendo YouTube', sourceKey: 'Nintendo', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgK_2VQWwigtTr_5TviGy2w' },
  { name: 'Bethesda YouTube', sourceKey: 'Bethesda', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvZHe-SP3xC7DdOk4Ri8QBw' },
  { name: 'CD Projekt Red YouTube', sourceKey: 'CD Projekt Red', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuCtanBJXOPAEIAUXf9944g' },
  { name: 'AMD Gaming YouTube', sourceKey: 'AMD Gaming', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCHQDjDDW8w2RieO-IuqYlyg' },
  { name: 'Konami YouTube', sourceKey: 'Konami', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCwkUBN7foWU9GcY5cFmso-Q' },
  { name: 'Ubisoft YouTube', sourceKey: 'Ubisoft', category: 'Gaming', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC0KU8F9jJqSLS11LRXvFWmg' },

  // ════════════════════════════════════════════════════════
  // 🎮 GAMING — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'Wario64 (deals/drops)', sourceKey: 'Wario64', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/Wario64/rss' },
  { name: 'Shinobi602 (insider)', sourceKey: 'Shinobi602', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/shinobi602/rss' },
  { name: 'BenjiSales (business)', sourceKey: 'BenjiSales', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/BenjiSales/rss' },
  { name: 'PlayStation Twitter', sourceKey: 'PlayStation', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/PlayStation/rss' },
  { name: 'Xbox Twitter', sourceKey: 'Xbox', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/Xbox/rss' },
  { name: 'Steam Twitter', sourceKey: 'Steam', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/Steam/rss' },
  { name: 'Rockstar Twitter', sourceKey: 'Rockstar Games', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/RockstarGames/rss' },
  { name: 'Konami Twitter', sourceKey: 'Konami', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/Konami/rss' },
  { name: 'Bandai Namco Twitter', sourceKey: 'Bandai Namco', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/BandaiNamcoUS/rss' },
  { name: 'Ubisoft Twitter', sourceKey: 'Ubisoft', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/Ubisoft/rss' },
  { name: 'Bethesda Twitter', sourceKey: 'Bethesda', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/bethesda/rss' },
  { name: 'CD Projekt Red Twitter', sourceKey: 'CD Projekt Red', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/CDPROJEKTRED/rss' },
  { name: 'Valve Twitter', sourceKey: 'Valve', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/valvesoftware/rss' },
  { name: 'WB Games Twitter', sourceKey: 'WB Games', category: 'Gaming', type: 'rss',
    url: 'https://xcancel.com/wbgames/rss' },

  // ════════════════════════════════════════════════════════
  // 🎬 TV & MOVIES — RSS
  // ════════════════════════════════════════════════════════
  { name: 'ComingSoon', category: 'TV & Movies', type: 'rss',
    url: 'https://www.comingsoon.net/feed' },
  { name: 'Variety', category: 'TV & Movies', type: 'rss',
    url: 'https://variety.com/feed/' },
  { name: 'Deadline', category: 'TV & Movies', type: 'rss',
    url: 'https://deadline.com/feed/' },
  { name: 'IndieWire', category: 'TV & Movies', type: 'rss',
    url: 'https://www.indiewire.com/feed' },
  { name: 'ComicBookMovie', category: 'TV & Movies', type: 'rss',
    url: 'https://www.comicbookmovie.com/rss/' },
  { name: 'Reddit r/television', category: 'TV & Movies', type: 'rss',
    url: 'https://reddit.com/r/television/.rss' },

  // ════════════════════════════════════════════════════════
  // 🎬 TV & MOVIES — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'A24 YouTube', sourceKey: 'A24', category: 'TV & Movies', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCuPivVjnfNo4mb3Oog_frZg' },
  { name: 'Max YouTube', sourceKey: 'Max', category: 'TV & Movies', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCx-KWLTKlB83hDI6UKECtJQ' },
  { name: 'Disney Plus YouTube', sourceKey: 'Disney Plus', category: 'TV & Movies', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_5niPa-d35gg88HaS7RrIw' },
  { name: 'Adult Swim YouTube', sourceKey: 'Adult Swim', category: 'TV & Movies', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1MEMnZEDKqLPu-B-AHIsyw' },
  { name: 'Netflix YouTube', sourceKey: 'Netflix', category: 'TV & Movies', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCWOA1ZGywLbqmigxE4Qlvuw' },
  { name: 'Warner Bros YouTube', sourceKey: 'Warner Bros', category: 'TV & Movies', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCjmJDM5pRKbUlVIzDYYWb6g' },

  // ════════════════════════════════════════════════════════
  // 🎬 TV & MOVIES — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'DiscussingFilm Twitter', sourceKey: 'DiscussingFilm', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/DiscussingFilm/rss' },
  { name: 'Culture Crave Twitter', sourceKey: 'Culture Crave', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/CultureCrave/rss' },
  { name: 'Hollywood Reporter Twitter', sourceKey: 'Hollywood Reporter', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/THR/rss' },
  { name: 'HBO Twitter', sourceKey: 'HBO', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/HBO/rss' },
  { name: 'HBO Max Twitter', sourceKey: 'HBO Max', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/HBOMAX/rss' },
  { name: 'Netflix Twitter', sourceKey: 'Netflix', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/netflix/rss' },
  { name: 'Warner Bros Twitter', sourceKey: 'Warner Bros', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/WarnerBros/rss' },
  { name: 'Adult Swim Twitter', sourceKey: 'Adult Swim', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/adultswim/rss' },
  { name: 'Disney Twitter', sourceKey: 'Disney', category: 'TV & Movies', type: 'rss',
    url: 'https://xcancel.com/Disney/rss' },

  // ════════════════════════════════════════════════════════
  // 🎙️ MEDIA ANNOUNCEMENTS — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'DC YouTube', sourceKey: 'DC', category: 'Media Announcements', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCiifkYAs_bq1pt_zbNAzYGg' },
  { name: 'Star Wars YouTube', sourceKey: 'Star Wars', category: 'Media Announcements', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCZGYJFUizSax-yElQaFDp5Q' },
  { name: 'Marvel Entertainment YouTube', sourceKey: 'Marvel Entertainment', category: 'Media Announcements', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvC4D8onUfXzvjTOM-dBfEA' },
  { name: 'Pixar YouTube', sourceKey: 'Pixar', category: 'Media Announcements', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_IRYSp4auq7hKLvziWVH6w' },

  // ════════════════════════════════════════════════════════
  // 🎙️ MEDIA ANNOUNCEMENTS — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'DC Universe Twitter', sourceKey: 'DC Universe', category: 'Media Announcements', type: 'rss',
    url: 'https://xcancel.com/TheDCUniverse/rss' },
  { name: 'Marvel Twitter', sourceKey: 'Marvel', category: 'Media Announcements', type: 'rss',
    url: 'https://xcancel.com/Marvel/rss' },

  // ════════════════════════════════════════════════════════
  // 🎌 ANIME — RSS
  // ════════════════════════════════════════════════════════
  { name: 'Anime News Network', category: 'Anime', type: 'rss',
    url: 'https://www.animenewsnetwork.com/all/rss.xml' },
  { name: 'Anime Corner', category: 'Anime', type: 'rss',
    url: 'https://animecorner.me/feed/' },

  // ════════════════════════════════════════════════════════
  // 🎌 ANIME — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'Toei Animation YouTube', sourceKey: 'Toei Animation', category: 'Anime', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCQYYekTKCb1y12sas08T6gQ' },

  // ════════════════════════════════════════════════════════
  // 🎌 ANIME — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'Toei Animation Twitter', sourceKey: 'Toei Animation', category: 'Anime', type: 'rss',
    url: 'https://xcancel.com/ToeiAnimation/rss' },

  // ════════════════════════════════════════════════════════
  // 🎨 ANIMATION — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'ToonHive Twitter', sourceKey: 'ToonHive', category: 'Animation', type: 'rss',
    url: 'https://xcancel.com/ToonHive/rss' },
  { name: 'Cartoon Base Twitter', sourceKey: 'Cartoon Base', category: 'Animation', type: 'rss',
    url: 'https://xcancel.com/TheCartoonBase/rss' },
  { name: 'Catsuka Twitter (indie/sakuga)', sourceKey: 'Catsuka', category: 'Animation', type: 'rss',
    url: 'https://xcancel.com/catsuka/rss' },

  // ════════════════════════════════════════════════════════
  // 🖥️ TECH & HARDWARE — RSS
  // ════════════════════════════════════════════════════════
  { name: 'The Verge', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.theverge.com/rss/index.xml' },
  { name: "Tom's Hardware", category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.tomshardware.com/feeds/all' },
  { name: 'Windows Central', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.windowscentral.com/rss.xml' },
  { name: 'Apple Newsroom', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.apple.com/newsroom/rss-feed.rss' },
  { name: 'Ars Technica', category: 'Tech & Hardware', type: 'rss',
    url: 'http://feeds.arstechnica.com/arstechnica/index' },
  { name: 'Gizmodo', category: 'Tech & Hardware', type: 'rss',
    url: 'https://gizmodo.com/rss' },
  { name: 'Engadget', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.engadget.com/rss.xml' },
  { name: 'Nvidia News', category: 'Tech & Hardware', type: 'rss',
    url: 'https://nvidianews.nvidia.com/releases.xml' },
  { name: 'Rest of World', category: 'Tech & Hardware', type: 'rss',
    url: 'https://restofworld.org/feed/' },
  { name: 'Wan Show (LTT)', category: 'Tech & Hardware', type: 'rss',
    url: 'https://feeds.megaphone.fm/LMG3928170156' },
  { name: 'AppleInsider', category: 'Tech & Hardware', type: 'rss',
    url: 'https://appleinsider.com/rss/news/' },
  { name: 'CNET', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.cnet.com/rss/news/' },
  { name: 'Wired', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.wired.com/feed/rss' },
  { name: 'Lifehacker', category: 'Tech & Hardware', type: 'rss',
    url: 'https://lifehacker.com/rss' },
  { name: 'TechCrunch', category: 'Tech & Hardware', type: 'rss',
    url: 'https://techcrunch.com/feed/' },

  // ════════════════════════════════════════════════════════
  // 🖥️ TECH & HARDWARE — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'Apple YouTube', sourceKey: 'Apple', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCYFQ33UIPERYx8-ZHucZbDA' },
  { name: 'Nvidia YouTube', sourceKey: 'Nvidia', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCHuiy8bXnmK5nisYHUd1J5g' },
  { name: 'AMD YouTube', sourceKey: 'AMD', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC3IHCD51zFpt28TkSBOKJpA' },
  { name: 'Google YouTube', sourceKey: 'Google', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCK8sQmJBp8GCxrOtXWBpyEA' },
  { name: 'CNETTV YouTube', sourceKey: 'CNETTV', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC852T8a3n65T2T0s_tS2rSQ' },
  { name: 'Marques Brownlee YouTube', sourceKey: 'Marques Brownlee', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ' },
  { name: 'Linus Tech Tips YouTube', sourceKey: 'Linus Tech Tips', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw' },
  { name: 'Unbox Therapy YouTube', sourceKey: 'Unbox Therapy', category: 'Tech & Hardware', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC7baTQivGsaGGLDqf7T81Cw' },

  // ════════════════════════════════════════════════════════
  // 🖥️ TECH & HARDWARE — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'The Verge Twitter', sourceKey: 'The Verge', category: 'Tech & Hardware', type: 'rss',
    url: 'https://xcancel.com/verge/rss' },
  { name: 'Microsoft Twitter', sourceKey: 'Microsoft', category: 'Tech & Hardware', type: 'rss',
    url: 'https://xcancel.com/Microsoft/rss' },
  { name: 'Apple Twitter', sourceKey: 'Apple', category: 'Tech & Hardware', type: 'rss',
    url: 'https://xcancel.com/Apple/rss' },
  { name: 'Nvidia Twitter', sourceKey: 'Nvidia', category: 'Tech & Hardware', type: 'rss',
    url: 'https://xcancel.com/nvidia/rss' },
  { name: 'Google Twitter', sourceKey: 'Google', category: 'Tech & Hardware', type: 'rss',
    url: 'https://xcancel.com/Google/rss' },
  { name: 'Sony Twitter', sourceKey: 'Sony', category: 'Tech & Hardware', type: 'rss',
    url: 'https://xcancel.com/Sony/rss' },

  // ════════════════════════════════════════════════════════
  // 🤖 AI & LLMs — RSS
  // ════════════════════════════════════════════════════════
  { name: 'Anthropic', category: 'AI & LLMs', type: 'rss',
    url: 'https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_claude.xml' },
  { name: 'Google Blog', category: 'AI & LLMs', type: 'rss',
    url: 'https://blog.google/rss/' },
  { name: 'OpenAI', category: 'AI & LLMs', type: 'rss',
    url: 'https://openai.com/news/rss.xml' },
  { name: 'VentureBeat AI', category: 'AI & LLMs', type: 'rss',
    url: 'https://venturebeat.com/category/ai/feed/' },
  { name: 'HuggingFace Daily Papers', category: 'AI & LLMs', type: 'rss',
    url: 'https://raw.githubusercontent.com/huangboming/huggingface-daily-paper-feed/refs/heads/main/feed.xml' },

  // ════════════════════════════════════════════════════════
  // 🤖 AI & LLMs — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'OpenAI YouTube', sourceKey: 'OpenAI', category: 'AI & LLMs', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXZCJLdBC09xxGZ6gcdrc6A' },
  { name: 'Anthropic YouTube', sourceKey: 'Anthropic', category: 'AI & LLMs', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCrDwWp7EBBv4NwvScIpBDOA' },

  // ════════════════════════════════════════════════════════
  // 🤖 AI & LLMs — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'OpenAI Twitter', sourceKey: 'OpenAI', category: 'AI & LLMs', type: 'rss',
    url: 'https://xcancel.com/OpenAI/rss' },
  { name: 'ChatGPT Twitter', sourceKey: 'ChatGPT', category: 'AI & LLMs', type: 'rss',
    url: 'https://xcancel.com/ChatGPT/rss' },
  { name: 'Anthropic Twitter', sourceKey: 'Anthropic', category: 'AI & LLMs', type: 'rss',
    url: 'https://xcancel.com/AnthropicAI/rss' },
  { name: 'Rowan Cheung Twitter', sourceKey: 'Rowan Cheung', category: 'AI & LLMs', type: 'rss',
    url: 'https://xcancel.com/rowancheung/rss' },
  { name: 'Bindu Reddy Twitter', sourceKey: 'Bindu Reddy', category: 'AI & LLMs', type: 'rss',
    url: 'https://xcancel.com/DisruptMatrix/rss' },

  // ════════════════════════════════════════════════════════
  
  // ════════════════════════════════════════════════════════
  // 🌍 WORLD NEWS — RSS
  // ════════════════════════════════════════════════════════
  { name: 'BBC World News', category: 'World News', type: 'rss',
    url: 'http://feeds.bbci.co.uk/news/world/rss.xml' },
  { name: 'Reddit r/worldnews', category: 'World News', type: 'rss',
    url: 'https://www.reddit.com/r/worldnews/.rss' },

  // ════════════════════════════════════════════════════════
  // 🌍 WORLD NEWS — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'Reuters YouTube', sourceKey: 'Reuters', category: 'World News', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UChqUTb7kYRX8-EiaN3XFrSQ' },

  // 🇺🇸 US POLITICS — RSS
  // ════════════════════════════════════════════════════════
  { name: 'AP News', category: 'US Politics', type: 'rss',
    url: 'https://news.google.com/rss/search?q=when:12h+allinurl:apnews.com&hl=en-US&gl=US&ceid=US:en' },
  { name: 'Reuters', category: 'US Politics', type: 'rss',
    url: 'https://news.google.com/rss/search?q=when:24h+allinurl:reuters.com&hl=en-US&gl=US&ceid=US:en' },
  
  { name: 'Politico', category: 'US Politics', type: 'rss',
    url: 'https://rss.politico.com/playbook.xml' },
  { name: 'Yahoo News', category: 'US Politics', type: 'rss',
    url: 'https://news.yahoo.com/rss/mostviewed' },
  { name: 'NY Post', category: 'US Politics', type: 'rss',
    url: 'https://nypost.com/feed/' },
  { name: 'Vox', category: 'US Politics', type: 'rss',
    url: 'https://vox.com/rss/index.xml' },
  { name: 'Politifact', category: 'US Politics', type: 'rss',
    url: 'https://politifact.com/rss/factchecks/' },
  { name: 'Politico Congress', category: 'US Politics', type: 'rss',
    url: 'http://rss.politico.com/congress.xml' },
  { name: 'Politico Politics News', category: 'US Politics', type: 'rss',
    url: 'https://rss.politico.com/politics-news.xml' },
  { name: 'Roll Call', category: 'US Politics', type: 'rss',
    url: 'https://rollcall.com/feed' },
  { name: 'NYT Homepage', category: 'US Politics', type: 'rss',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml' },

  // ════════════════════════════════════════════════════════
  // 🇺🇸 US POLITICS — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'White House YouTube', sourceKey: 'White House', category: 'US Politics', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCYxRlFDqcWM4y7FfpiAN3KQ' },
  { name: 'C-SPAN YouTube', sourceKey: 'C-SPAN', category: 'US Politics', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCb--64Gl51jIEVE-GLDAVTg' },

  // ════════════════════════════════════════════════════════
  // 🔭 SCIENCE & SPACE — RSS
  // ════════════════════════════════════════════════════════
  { name: 'Phys.org', category: 'Science & Space', type: 'rss',
    url: 'https://phys.org/rss-feed/' },
  { name: 'NASA Breaking News', sourceKey: 'NASA', category: 'Science & Space', type: 'rss',
    url: 'https://www.nasa.gov/rss/dyn/breaking_news.rss' },
  { name: 'Space.com', category: 'Science & Space', type: 'rss',
    url: 'https://www.space.com/feeds/all' },

  // ════════════════════════════════════════════════════════
  // 🔒 SECURITY — RSS
  // ════════════════════════════════════════════════════════
  { name: 'Krebs on Security', category: 'Security', type: 'rss',
    url: 'https://krebsonsecurity.com/feed/' },
  { name: 'TorrentFreak', category: 'Security', type: 'rss',
    url: 'https://torrentfreak.com/feed/' },

  // ════════════════════════════════════════════════════════
  // 📚 COMICS — RSS
  // ════════════════════════════════════════════════════════
  { name: 'ComicList', category: 'Comics', type: 'rss',
    url: 'https://ncrl.blogspot.com/feeds/posts/default?alt=rss' },
  { name: 'CBR Comics', category: 'Comics', type: 'rss',
    url: 'https://www.cbr.com/feed/' },
  { name: 'AIPT Comics', category: 'Comics', type: 'rss',
    url: 'https://aiptcomics.com/feed/' },
  { name: 'ComicBookMovie', category: 'Comics', type: 'rss',
    url: 'https://www.comicbookmovie.com/rss/' },

  // ════════════════════════════════════════════════════════
  // 📚 COMICS — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'AIPT Comics Twitter', sourceKey: 'AIPT Comics', category: 'Comics', type: 'rss',
    url: 'https://xcancel.com/AIPTcomics/rss' },
  { name: 'The Beat Twitter', sourceKey: 'The Beat', category: 'Comics', type: 'rss',
    url: 'https://xcancel.com/ComicsBeat/rss' },
  { name: 'ComicBook.com Twitter', sourceKey: 'ComicBook.com', category: 'Comics', type: 'rss',
    url: 'https://xcancel.com/ComicBook/rss' },

  // ════════════════════════════════════════════════════════
  
  // ════════════════════════════════════════════════════════
  // 💼 BUSINESS & FINANCE — RSS
  // ════════════════════════════════════════════════════════
  { name: 'Billboard', category: 'Business & Finance', type: 'rss',
    url: 'https://www.billboard.com/articles/rss.xml' },

  // ════════════════════════════════════════════════════════
  // 💼 BUSINESS & FINANCE — YouTube
  // ════════════════════════════════════════════════════════
  { name: 'Bloomberg YouTube', sourceKey: 'Bloomberg', category: 'Business & Finance', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCd6MoBMJkGgB3L5v_yL13sQ' },
  { name: 'Business Insider YouTube', sourceKey: 'Business Insider', category: 'Business & Finance', type: 'rss',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6nOt9O0sJ1U4T_w3B-fLTA' },

  // ════════════════════════════════════════════════════════
  // 👁️ BLINDSPOT ANALYSIS
  // ════════════════════════════════════════════════════════

  // 🔮 NOTABLE TRENDS
  // ════════════════════════════════════════════════════════
  { name: 'Hacker News', category: 'Notable Trends', type: 'rss',
    url: 'https://news.ycombinator.com/rss' },
  { name: 'Castle Super Beast', category: 'Notable Trends', type: 'rss',
    url: 'https://rss.libsyn.com/shows/46822/destinations/156361.xml' },
  { name: 'Wikipedia Current Events (history)', category: 'Notable Trends', type: 'rss',
    url: 'https://en.wikipedia.org/w/index.php?title=Portal:Current_events&action=history&feed=atom' },
  { name: 'Wikipedia Current Events (Google proxy)', category: 'Notable Trends', type: 'rss',
    url: 'https://news.google.com/rss/search?q=when:24h+site:en.wikipedia.org+Current+events&hl=en-US&gl=US&ceid=US:en' },
  { name: 'Google Trends', category: 'Notable Trends', type: 'rss',
    url: 'https://trends.google.com/trends/trendingsearches/daily/rss?geo=US' },
  { name: 'Reddit r/news', category: 'Notable Trends', type: 'rss',
    url: 'https://www.reddit.com/r/news/.rss' },
  { name: 'Reddit r/outoftheloop', category: 'Notable Trends', type: 'rss',
    url: 'https://www.reddit.com/r/outoftheloop/.rss' },

  // ════════════════════════════════════════════════════════
  // 🕵️ LEAKS & RUMORS — RSS
  // ════════════════════════════════════════════════════════
  { name: 'Insider Gaming', category: 'Leaks & Rumors', type: 'rss',
    url: 'https://insider-gaming.com/feed/' },
  { name: 'VideoGamesChronicle', sourceKey: 'VGC', category: 'Leaks & Rumors', type: 'rss',
    url: 'https://www.videogameschronicle.com/feed/' },
  { name: 'Giant Freakin Robot', category: 'Leaks & Rumors', type: 'rss',
    url: 'https://www.giantfreakinrobot.com/feed' },
  { name: 'Reddit r/gamingleaksandrumours', category: 'Leaks & Rumors', type: 'rss',
    url: 'https://www.reddit.com/r/gamingleaksandrumours/.rss' },

  // ════════════════════════════════════════════════════════
  // 🕵️ LEAKS & RUMORS — xCancel
  // ════════════════════════════════════════════════════════
  { name: 'Tom Henderson Twitter (insider)', sourceKey: 'Tom Henderson', category: 'Leaks & Rumors', type: 'rss',
    url: 'https://xcancel.com/_Tom_Henderson_/rss' },
  { name: 'The Snitch Twitter (cryptic leaks)', sourceKey: 'The Snitch', category: 'Leaks & Rumors', type: 'rss',
    url: 'https://xcancel.com/insider_wtf/rss' },

];
