// GENERATED by scripts/gen-catalog.mjs from n8n node "Normalize & Tag" — do not hand-edit.
import type { SourceTag } from './types.js';

export const SOURCE_MAP: Record<string, SourceTag> = {
  // ── Gaming RSS ────────────────────────────────────────
  'blog.playstation.com':    { name: 'PlayStation Blog',    category: 'Gaming' },
  'feedburner.com':          { name: 'PlayStation Blog',    category: 'Gaming' },
  'nintendo.com':            { name: 'Nintendo',            category: 'Gaming' },
  'news.xbox.com':           { name: 'Xbox Wire',           category: 'Gaming' },
  'xbox.com':                { name: 'Xbox',                category: 'Gaming' },
  'steampowered.com':        { name: 'Steam News',          category: 'Gaming' },
  'ign.com':                 { name: 'IGN',                 category: 'Gaming' },
  'kotaku.com':              { name: 'Kotaku',              category: 'Gaming' },
  'polygon.com':             { name: 'Polygon',             category: 'Gaming' },
  'eurogamer.net':           { name: 'Eurogamer',           category: 'Gaming' },
  'rockpapershotgun.com':    { name: 'Rock Paper Shotgun',  category: 'Gaming' },
  'callofduty.com':          { name: 'Call of Duty',        category: 'Gaming' },
  'ageofempires.com':        { name: 'Age of Empires',      category: 'Gaming' },
  'pcgamer.com':             { name: 'PC Gamer',            category: 'Gaming' },
  // ── TV & Movies RSS ───────────────────────────────────
  'comingsoon.net':          { name: 'ComingSoon',          category: 'TV & Movies' },
  'variety.com':             { name: 'Variety',             category: 'TV & Movies' },
  'deadline.com':            { name: 'Deadline',            category: 'TV & Movies' },
  'indiewire.com':           { name: 'IndieWire',           category: 'TV & Movies' },
  'comicbookmovie.com':      { name: 'ComicBookMovie',      category: 'TV & Movies' },
  'ew.com':                  { name: 'Entertainment Weekly',category: 'TV & Movies' },
  // ── Tech & Hardware RSS ───────────────────────────────
  'theverge.com':            { name: 'The Verge',           category: 'Tech & Hardware' },
  'tomshardware.com':        { name: "Tom's Hardware",      category: 'Tech & Hardware' },
  'windowscentral.com':      { name: 'Windows Central',     category: 'Tech & Hardware' },
  'apple.com':               { name: 'Apple Newsroom',      category: 'Tech & Hardware' },
  'arstechnica.com':         { name: 'Ars Technica',        category: 'Tech & Hardware' },
  'gizmodo.com':             { name: 'Gizmodo',             category: 'Tech & Hardware' },
  'engadget.com':            { name: 'Engadget',            category: 'Tech & Hardware' },
  'nvidianews.nvidia.com':   { name: 'Nvidia News',         category: 'Tech & Hardware' },
  'blogs.nvidia.com':        { name: 'Nvidia Blog',         category: 'Tech & Hardware' },
  'restofworld.org':         { name: 'Rest of World',       category: 'Tech & Hardware' },
  'feeds.megaphone.fm':      { name: 'Wan Show',            category: 'Tech & Hardware' },
  'lifehacker.com':          { name: 'Lifehacker',          category: 'Tech & Hardware' },
  'techcrunch.com':          { name: 'TechCrunch',          category: 'Tech & Hardware' },
  // ── AI & LLMs RSS ─────────────────────────────────────
  'raw.githubusercontent.com': { name: 'Anthropic',         category: 'AI & LLMs' },
  'anthropic.com':           { name: 'Anthropic',           category: 'AI & LLMs' },
  'claude.com':              { name: 'Anthropic',           category: 'AI & LLMs' },
  'blog.google':             { name: 'Google Blog',         category: 'AI & LLMs' },
  'openai.com':              { name: 'OpenAI',              category: 'AI & LLMs' },
  'venturebeat.com':         { name: 'VentureBeat AI',      category: 'AI & LLMs' },
  'huggingface.co':          { name: 'HuggingFace Papers',  category: 'AI & LLMs' },
  'arxiv.org':               { name: 'arXiv',               category: 'AI & LLMs' },
  // ── US Politics RSS ───────────────────────────────────
  'apnews.com':              { name: 'AP News',             category: 'US Politics' },
  'reuters.com':             { name: 'Reuters',             category: 'US Politics' },
  'bbci.co.uk':              { name: 'BBC World News',      category: 'World News' },
  'bbc.co.uk':               { name: 'BBC World News',      category: 'World News' },
  'politico.com':            { name: 'Politico',            category: 'US Politics' },
  'yahoo.com':               { name: 'Yahoo News',          category: 'US Politics' },
  'news.yahoo.com':          { name: 'Yahoo News',          category: 'US Politics' },
  'news.google.com':         { name: 'Google News',         category: 'US Politics' },
  // ── Science & Space RSS ───────────────────────────────
  'phys.org':                { name: 'Phys.org',            category: 'Science & Space' },
  'nasa.gov':                { name: 'NASA',                category: 'Science & Space' },
  'space.com':               { name: 'Space.com',           category: 'Science & Space' },
  // ── Security RSS ──────────────────────────────────────
  'krebsonsecurity.com':     { name: 'Krebs on Security',   category: 'Security' },
  'torrentfreak.com':        { name: 'TorrentFreak',        category: 'Security' },
  // ── Comics RSS ────────────────────────────────────────
  'ncrl.blogspot.com':       { name: 'ComicList',           category: 'Comics' },
  'cbr.com':                 { name: 'CBR',                 category: 'Comics' },
  'aiptcomics.com':          { name: 'AIPT Comics',         category: 'Comics' },
  // ── Anime RSS ─────────────────────────────────────────
  'animenewsnetwork.com':    { name: 'Anime News Network',  category: 'Anime' },
  'animecorner.me':          { name: 'Anime Corner',        category: 'Anime' },
  // ── Reddit (Various) ──────────────────────────────────
  'reddit.com/r/games':                 { name: 'Reddit r/games',                 category: 'Gaming' },
  'reddit.com/r/gamingleaksandrumours': { name: 'Reddit r/gamingleaksandrumours', category: 'Leaks & Rumors' },
  'reddit.com/r/news':                  { name: 'Reddit r/news',                  category: 'Notable Trends' },
  'reddit.com/r/outoftheloop':          { name: 'Reddit r/outoftheloop',          category: 'Notable Trends' },
  'reddit.com/r/worldnews':             { name: 'Reddit r/worldnews',             category: 'World News' },
  'reddit.com/r/television':            { name: 'Reddit r/television',            category: 'TV & Movies' },
  'reddit.com':                         { name: 'Reddit',                         category: 'Notable Trends' },
  // ── Business & Finance ──
  'billboard.com':           { name: 'Billboard',           category: 'Business & Finance' },
  // ── Blindspot Analysis ──
  // ── Notable Trends RSS ────────────────────────────────
  'hnrss.org':               { name: 'Hacker News',         category: 'Notable Trends' },
  'news.ycombinator.com':    { name: 'Hacker News',         category: 'Notable Trends' },
  'rss.libsyn.com':          { name: 'Castle Super Beast',  category: 'Notable Trends' },
  'wikipedia.org':           { name: 'Wikipedia',           category: 'Notable Trends' },
  'trends.google.com':       { name: 'Google Trends',       category: 'Notable Trends' },
  // ── Leaks & Rumors RSS ────────────────────────────────
  'insider-gaming.com':      { name: 'Insider Gaming',      category: 'Leaks & Rumors' },
  'videogameschronicle.com': { name: 'VGC',                 category: 'Leaks & Rumors' },
  'giantfreakinrobot.com':   { name: 'Giant Freakin Robot', category: 'Leaks & Rumors' },
};

export const YOUTUBE_AUTHORS: Record<string, SourceTag> = {
  // Gaming
  'IGN':                                { name: 'IGN',                    category: 'Gaming' },
  'Xbox':                               { name: 'Xbox',                   category: 'Gaming' },
  'Valve':                              { name: 'Valve',                  category: 'Gaming' },
  'FromSoftware':                       { name: 'FromSoftware',           category: 'Gaming' },
  'FromSoftware, Inc.':                 { name: 'FromSoftware',           category: 'Gaming' },
  'Rockstar Games':                     { name: 'Rockstar Games',         category: 'Gaming' },
  'Rockstar Games UK & Ireland':        { name: 'Rockstar Games',         category: 'Gaming' },
  'PlayStation':                        { name: 'PlayStation',            category: 'Gaming' },
  'Bandai Namco Entertainment America': { name: 'Bandai Namco',           category: 'Gaming' },
  'Bandai Namco Entertainment':         { name: 'Bandai Namco',           category: 'Gaming' },
  'WB Games':                           { name: 'WB Games',               category: 'Gaming' },
  'Nintendo':                           { name: 'Nintendo',               category: 'Gaming' },
  'Play Nintendo':                      { name: 'Nintendo',               category: 'Gaming' },
  'Bethesda Softworks':                 { name: 'Bethesda',               category: 'Gaming' },
  'CD PROJEKT RED':                     { name: 'CD Projekt Red',         category: 'Gaming' },
  'AMD':                                { name: 'AMD Gaming',             category: 'Gaming' },
  'Konami':                             { name: 'Konami',                 category: 'Gaming' },
  'Ubisoft':                            { name: 'Ubisoft',                category: 'Gaming' },
  'Forza Motorsport':                   { name: 'Forza',                  category: 'Gaming' },
  'Forza':                              { name: 'Forza',                  category: 'Gaming' },
  'Steam':                              { name: 'Steam',                  category: 'Gaming' },
  'Marathon':                           { name: 'Marathon',               category: 'Gaming' },
  'Hogwarts Legacy':                    { name: 'Hogwarts Legacy',        category: 'Gaming' },
  // Tech
  'Apple':                              { name: 'Apple',                  category: 'Tech & Hardware' },
  'Apple Support':                      { name: 'Apple Support',          category: 'Tech & Hardware' },
  'NVIDIA':                             { name: 'Nvidia',                 category: 'Tech & Hardware' },
  'Google':                             { name: 'Google',                 category: 'Tech & Hardware' },
  'CNET':                               { name: 'CNETTV',                 category: 'Tech & Hardware' },
  'CNETTV':                             { name: 'CNETTV',                 category: 'Tech & Hardware' },
  'Marques Brownlee':                   { name: 'Marques Brownlee',       category: 'Tech & Hardware' },
  'Linus Tech Tips':                    { name: 'Linus Tech Tips',        category: 'Tech & Hardware' },
  'Unbox Therapy':                      { name: 'Unbox Therapy',          category: 'Tech & Hardware' },
  // AI
  'OpenAI':                             { name: 'OpenAI',                 category: 'AI & LLMs' },
  'Anthropic':                          { name: 'Anthropic',              category: 'AI & LLMs' },
  // TV & Movies
  'Disney':                             { name: 'Disney',                 category: 'TV & Movies' },
  'A24':                                { name: 'A24',                    category: 'TV & Movies' },
  'Max':                                { name: 'Max',                    category: 'TV & Movies' },
  'HBO Max':                            { name: 'Max',                    category: 'TV & Movies' },
  'Disney+':                            { name: 'Disney+',                category: 'TV & Movies' },
  'Walt Disney Studios':                { name: 'Disney',                 category: 'TV & Movies' },
  'Adult Swim':                         { name: 'Adult Swim',             category: 'TV & Movies' },
  'Netflix':                            { name: 'Netflix',                category: 'TV & Movies' },
  'Warner Bros.':                       { name: 'Warner Bros',            category: 'TV & Movies' },
  'Warner Bros. Pictures':              { name: 'Warner Bros',            category: 'TV & Movies' },
  'Warner Bros. Entertainment':         { name: 'Warner Bros',            category: 'TV & Movies' },
  'Rick and Morty':                     { name: 'Rick and Morty',         category: 'TV & Movies' },
  // Media Announcements
  'DC':                                 { name: 'DC',                     category: 'Media Announcements' },
  'Star Wars':                          { name: 'Star Wars',              category: 'Media Announcements' },
  'Marvel Entertainment':               { name: 'Marvel',                 category: 'Media Announcements' },
  'Pixar':                              { name: 'Pixar',                  category: 'Media Announcements' },
  // Anime
  'Toei Animation':                     { name: 'Toei Animation',         category: 'Anime' },
  'Toei Animation Inc.':                { name: 'Toei Animation',         category: 'Anime' },
  // Politics
  'The White House':                    { name: 'White House',            category: 'US Politics' },
  'C-SPAN':                             { name: 'C-SPAN',                 category: 'US Politics' },
  // World News
  'Reuters':                            { name: 'Reuters',                category: 'World News' },
  // Business & Finance
  'Bloomberg':                          { name: 'Bloomberg',              category: 'Business & Finance' },
  'Bloomberg Television':               { name: 'Bloomberg',              category: 'Business & Finance' },
  'Business Insider':                   { name: 'Business Insider',       category: 'Business & Finance' },
  // Notable Trends
  'Philip DeFranco':                    { name: 'Philip DeFranco',        category: 'Notable Trends' },
};

export const XCANCEL_USERS: Record<string, SourceTag> = {
  // Gaming
  'wario64': { name: 'Wario64', category: 'Gaming' },
  'shinobi602': { name: 'Shinobi602', category: 'Gaming' },
  'benjisales': { name: 'BenjiSales', category: 'Gaming' },
  'playstation': { name: 'PlayStation', category: 'Gaming' },
  'xbox': { name: 'Xbox', category: 'Gaming' },
  'steam': { name: 'Steam', category: 'Gaming' },
  'rockstargames': { name: 'Rockstar Games', category: 'Gaming' },
  'konami': { name: 'Konami', category: 'Gaming' },
  'bandainamcous': { name: 'Bandai Namco', category: 'Gaming' },
  'ubisoft': { name: 'Ubisoft', category: 'Gaming' },
  'bethesda': { name: 'Bethesda', category: 'Gaming' },
  'cdprojektred': { name: 'CD Projekt Red', category: 'Gaming' },
  'valvesoftware': { name: 'Valve', category: 'Gaming' },
  'wbgames': { name: 'WB Games', category: 'Gaming' },
  // TV & Movies
  'discussingfilm': { name: 'DiscussingFilm', category: 'TV & Movies' },
  'culturecrave': { name: 'Culture Crave', category: 'TV & Movies' },
  'thr': { name: 'Hollywood Reporter', category: 'TV & Movies' },
  'hbo': { name: 'HBO', category: 'TV & Movies' },
  'hbomax': { name: 'HBO Max', category: 'TV & Movies' },
  'netflix': { name: 'Netflix', category: 'TV & Movies' },
  'warnerbros': { name: 'Warner Bros', category: 'TV & Movies' },
  'adultswim': { name: 'Adult Swim', category: 'TV & Movies' },
  'disney': { name: 'Disney', category: 'TV & Movies' },
  // Media Announcements
  'thedcuniverse': { name: 'DC Universe', category: 'Media Announcements' },
  'marvel': { name: 'Marvel', category: 'Media Announcements' },
  // Anime
  'toeianimation': { name: 'Toei Animation', category: 'Anime' },
  // Animation
  'toonhive': { name: 'ToonHive', category: 'Animation' },
  'thecartoonbase': { name: 'Cartoon Base', category: 'Animation' },
  'catsuka': { name: 'Catsuka', category: 'Animation' },
  // Tech
  'verge': { name: 'The Verge', category: 'Tech & Hardware' },
  'microsoft': { name: 'Microsoft', category: 'Tech & Hardware' },
  'apple': { name: 'Apple', category: 'Tech & Hardware' },
  'nvidia': { name: 'Nvidia', category: 'Tech & Hardware' },
  'google': { name: 'Google', category: 'Tech & Hardware' },
  'sony': { name: 'Sony', category: 'Tech & Hardware' },
  // AI
  'openai': { name: 'OpenAI', category: 'AI & LLMs' },
  'chatgpt': { name: 'ChatGPT', category: 'AI & LLMs' },
  'anthropicai': { name: 'Anthropic', category: 'AI & LLMs' },
  'rowancheung': { name: 'Rowan Cheung', category: 'AI & LLMs' },
  'disruptmatrix': { name: 'Bindu Reddy', category: 'AI & LLMs' },
  // Comics
  'aiptcomics': { name: 'AIPT Comics', category: 'Comics' },
  'comicsbeat': { name: 'The Beat', category: 'Comics' },
  'comicbook': { name: 'ComicBook.com', category: 'Comics' },
  // Leaks & Rumors
  '_tom_henderson_': { name: 'Tom Henderson', category: 'Leaks & Rumors' },
  'insider_wtf': { name: 'The Snitch', category: 'Leaks & Rumors' },
  // Notable Trends
  'phillyd': { name: 'Philip DeFranco', category: 'Notable Trends' },
  'pubity': { name: 'Pubity', category: 'Notable Trends' },
};

export const PER_SOURCE_CAP = 8;
