// One-off generator: lifts the catalog data VERBATIM out of the deployed n8n Code nodes
// (../n8n-export/nodes) so the port can't drift from what was actually running.
// Re-run only if you deliberately re-sync from a newer n8n export.
import fs from 'node:fs';
import path from 'node:path';

const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1'));
const nodes = path.resolve(here, '../../n8n-export/nodes');
const out = path.resolve(here, '../src/catalog');

const slice = (src, startMarker, endMarker) => {
  const a = src.indexOf(startMarker);
  const b = src.indexOf(endMarker, a);
  if (a < 0 || b < 0) throw new Error(`marker not found: ${startMarker}`);
  return src.slice(a, b + endMarker.length);
};

const feedSrc = fs.readFileSync(path.join(nodes, 'Feed List Code.js'), 'utf8');
const feeds = slice(feedSrc, 'const FEEDS = [', '\n];');
fs.writeFileSync(path.join(out, 'feeds.generated.ts'),
`// GENERATED by scripts/gen-catalog.mjs from n8n node "Feed List Code" — do not hand-edit.
// To add a source, edit src/catalog/feeds.extra.ts instead (see README).
import type { FeedDef } from './types.js';

export ${feeds.replace('const FEEDS = [', 'const FEEDS: FeedDef[] = [')}
`);

const normSrc = fs.readFileSync(path.join(nodes, 'Normalize _ Tag.js'), 'utf8');
const sourceMap = slice(normSrc, 'const SOURCE_MAP = {', '\n};');
const ytAuthors = slice(normSrc, 'const YOUTUBE_AUTHORS = {', '\n};');
const xUsers = slice(normSrc, 'const XCANCEL_USERS = {', '\n};');
const cap = normSrc.match(/const PER_SOURCE_CAP = (\d+);/)[1];
fs.writeFileSync(path.join(out, 'sourceMap.generated.ts'),
`// GENERATED by scripts/gen-catalog.mjs from n8n node "Normalize & Tag" — do not hand-edit.
import type { SourceTag } from './types.js';

export ${sourceMap.replace('const SOURCE_MAP = {', 'const SOURCE_MAP: Record<string, SourceTag> = {')}

export ${ytAuthors.replace('const YOUTUBE_AUTHORS = {', 'const YOUTUBE_AUTHORS: Record<string, SourceTag> = {')}

export ${xUsers.replace('const XCANCEL_USERS = {', 'const XCANCEL_USERS: Record<string, SourceTag> = {')}

export const PER_SOURCE_CAP = ${cap};
`);
console.log('catalog generated');
